maintainer "James Harton, Sociable Limited."
maintainer_email "james@sociable.co.nz"
license "MIT"
description "Installs passenger via rubygems. Need rbenv installed gems"
version "0.0.1"
recipe "passenger", "Install passenger/nginx as a service."
